### ISSUE TITLE
小程序端第一次进入会白屏，并显示报错，从新进入后可运行，报错依旧存在

### ISSUE THREAD

**Issue by cander0815** [SilurianYang/uni-simple-router#425]
**问题描述**
打包后，小程序第一次进入会白屏，控制台出显现下面两种报错，从新进入小程序后，报错依旧存在，但是可以正常运行了。

**复现步骤**
报错1
```
"<TypeError: undefined is not an object (evaluating 'r.page')>
https://usr//app-service.js:4603:20675
beforeCreate@https://usr//app-service.js:4603:14823
Xe@https://usr//app-service.js:4615:11939
Cr@https://usr//app-service.js:4615:29430
https://usr//app-service.js:4615:34760
a@https://usr//app-service.js:4615:36107
attached@https://usr//app-service.js:4609:87184
https://lib/WASubContext.js:1:477503
https://lib/WASubContext.js:1:477392
t@https://lib/WASubContext.js:1:498123
t@https://lib/WASubContext.js:1:498435
t@https://lib/WASubContext.js:1:498377
t@https://lib/WASubContext.js:1:498435
t@https://lib/WASubContext.js:1:498435
t@https://lib/WASubContext.js:1:498435
t@https://lib/WASubContext.js:1:498377
t@https://lib/WASubContext.js:1:498435
t@https://lib/WASubContext.js:1:498377
t@https://lib/WASubContext.js:1:498435
t@https://lib/WASubContext.js:1:498435
t@https://lib/WASubContext.js:1:498377
f@https://lib/WASubContext.js:1:498445
https://lib/WASubContext.js:1:510474
Wa@https://lib/WASubContext.js:1:684825
https://lib/WASubContext.js:1:733477
https://lib/WASubContext.js:1:701769
https://lib/WASubContext.js:1:738928
https://lib/WASubContext.js:1:701769
https://lib/WASubContext.js:1:740566
https://lib/WASubContext.js:1:701769
wr@https://lib/WASubContext.js:1:746842
https://lib/WASubContext.js:1:700907
https://lib/WAServiceMainContext.js:1:760882
emit@https://lib/WAServiceMainContext.js:1:757633
emit@[native code]
https://lib/WAServiceMainContext.js:1:2371037
https://lib/WAServiceMainContext.js:1:767712
https://lib/WAServiceMainContext.js:1:760981
emit@https://lib/WAServiceMainContext.js:1:757633
https://lib/WAServiceMainContext.js:1:819189
https://lib/WAServiceMainContext.js:1:795871
emit@https://lib/WAServiceMainContext.js:1:82462
emit@[native code]
emit@https://lib/WAServiceMainContext.js:1:82081
subscribeHandler@https://lib/WAServiceMainContext.js:1:84730
global code"
```
报错二
```
"MiniProgramError
undefined is not an object (evaluating 'i.$scope._$vueId')
TypeError: undefined is not an object (evaluating 'i.$scope._$vueId')
at Or (app-service.js:4609:85170)
at jr (app-service.js:4609:85894)
at  (WASubContext.js:1:618726)
at  (WASubContext.js:1:477503)
at  (WASubContext.js:1:477392)
at r (WASubContext.js:1:481239)
at  (WASubContext.js:1:482018)
at l (WASubContext.js:1:480698)
at  (WASubContext.js:1:481865)
at  (WASubContext.js:1:482133)
at  (WASubContext.js:1:508687)
at _r (app-service.js:4609:85348)
at attached (app-service.js:4609:87127) 
at  (WASubContext.js:1:477503) 
at  (WASubContext.js:1:477392) 
at t (WASubContext.js:1:498123) 
at t (WASubContext.js:1:498435) 
at t (WASubContext.js:1:498435) 
at t (WASubContext.js:1:498435) 
at t (WASubContext.js:1:498435) 
at t (WASubContext.js:1:498377) 
at t (WASubContext.js:1:498435) 
at t (WASubContext.js:1:498435) 
at t (WASubContext.js:1:498377) 
at f (WASubContext.js:1:498445) 
at  (WASubContext.js:1:510474) 
at Wa (WASubContext.js:1:684825) 
at  (WASubContext.js:1:733477) 
at  (WASubContext.js:1:701769) 
at  (WASubContext.js:1:738928) 
at  (WASubContext.js:1:701769) 
at  (WASubContext.js:1:740566) 
at  (WASubContext.js:1:701769) 
at wr (WASubContext.js:1:746842) 
at  (WASubContext.js:1:700907) 
at  (WAServiceMainContext.js:1:760882) 
at emit (WAServiceMainContext.js:1:757633) 
at emit (native code) 
at  (WAServiceMainContext.js:1:2371037) 
at  (WAServiceMainContext.js:1:767712) 
at  (WAServiceMainContext.js:1:760981) 
at emit (WAServiceMainContext.js:1:757633) 
at  (WAServiceMainContext.js:1:819189) 
at  (WAServiceMainContext.js:1:795871) 
at emit (WAServiceMainContext.js:1:82462) 
at emit (native code) 
at emit (WAServiceMainContext.js:1:82081) 
at subscribeHandler (WAServiceMainContext.js:1:84730) 
global code"
```
错误三
```
"MiniProgramError 
undefined is not an object (evaluating 'this.$vm.$mp.query=e') 
TypeError: undefined is not an object (evaluating 'this.$vm.$mp.query=e') 
at  (app-service.js:4609:88158) 
at  (WASubContext.js:1:717365) 
at  (native code) 
at  (WASubContext.js:1:717158) 
at  (WASubContext.js:1:734354) 
at  (WASubContext.js:1:701769) 
at  (WASubContext.js:1:738928) 
at  (WASubContext.js:1:701769) 
at  (WASubContext.js:1:740566) 
at  (WASubContext.js:1:701769) 
at wr (WASubContext.js:1:746842) 
at  (WASubContext.js:1:700907) 
at  (WAServiceMainContext.js:1:760882) 
at emit (WAServiceMainContext.js:1:757633) 
at emit (native code) 
at  (WAServiceMainContext.js:1:2371037) 
at  (WAServiceMainContext.js:1:767712) 
at  (WAServiceMainContext.js:1:760981) 
at emit (WAServiceMainContext.js:1:757633) 
at  (WAServiceMainContext.js:1:819189) 
at  (WAServiceMainContext.js:1:795871) 
at emit (WAServiceMainContext.js:1:82462) 
at emit (native code) 
at emit (WAServiceMainContext.js:1:82081) 
at subscribeHandler (WAServiceMainContext.js:1:84730) 
global code"

```
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 iOS 12.1.2
 - 项目创建方法 Vue-cli
 - 设备信息 iPhone12
 - uni-simple-router版本  "version": "2.0.7",

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by SilurianYang** [comment]
可否提供相应的demo，我这边可以直接运行查看
